channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python
  - pip:
      - numpy
      - matplotlib
      - h5py
      - bilby
      - pandas
      - seaborn
      - lalsuite
      - latex
      - pyarrow
      - scipy