channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python
  - numpy
  - matplotlib
  - h5py
  - pandas
  - seaborn
  - scipy
  - pip:
      - bilby
      - lalsuite
      - latex
      - pyarrow